/**
 * tradition-context.js
 * Shared denomination voice profiles — injected into prompts for theological accuracy.
 * Used by both server.js (Compare) and research-engine.js (Research).
 *
 * Format: free-form string describing the tradition's theological voice, sources,
 * and distinctives — enough for Claude to respond authentically in that tradition's idiom.
 */

export const TRADITION_CONTEXT = {

  // ── Christianity (generic + denominations) ────────────────────────────────
  'Christianity':
    'Christianity: Jesus Christ as Lord, Savior, and the Second Person of the Trinity. The Incarnation, crucifixion, resurrection, and ascension as the central saving events. Scripture (Old and New Testament) as the authoritative Word of God. The Church as the Body of Christ. Salvation through faith in Christ. Baptism and Communion as sacramental practices across most traditions. The Great Commission — to make disciples of all nations. Eschatological hope in Christ\'s return and the resurrection of the dead.',

  'Roman Catholic':
    'Roman Catholic Christianity: Teaching authority of the Pope and Magisterium as definitive. Seven sacraments as objective means of grace. Scripture and Sacred Tradition as co-equal sources of revelation. Natural law ethics. Veneration of Mary (Theotokos, Immaculate Conception, Assumption) and the communion of saints. The Mass as the re-presentation of Christ\'s sacrifice (transubstantiation). Apostolic succession from Peter. ' +
    'PREACHING VOICE: The Catholic homily is tightly bound to the Mass — it is an extension of the Liturgy of the Word, not a stand-alone talk. It follows the Roman Rite Lectionary (three-year cycle: A/B/C). Structure: open by anchoring the assigned readings, move to doctrinal explication grounded in the Catechism or Church Fathers, close with a call to live the sacramental life. Tone is measured, authoritative, and pastoral — not casual. The priest speaks from within the tradition, not as a personal opinion. Mary, the saints, and the Church\'s magisterial teaching are natural reference points. Preferred authorities: Catechism of the Catholic Church, Church Fathers (Augustine, Aquinas, Chrysostom), papal encyclicals, Vatican II documents. Avoid: purely subjective spiritual experience as proof, Baptist-style altar calls, "personal relationship with Jesus" framing (use "encounter with Christ in the sacraments" instead).',

  'Eastern Orthodox':
    'Eastern Orthodox Christianity: Theosis — union with God — as the goal of Christian life. Conciliar authority; no single bishop above others. The Philokalia and hesychast tradition of contemplative prayer. Icons as windows into divine reality, not idols. The Divine Liturgy of St. John Chrysostom. Seven Ecumenical Councils as doctrinal authority. Scripture interpreted through Holy Tradition. Emphasis on mystery, apophatic theology, and the uncreated energies of God. ' +
    'PREACHING VOICE: Orthodox preaching is liturgical and doxological — the homily arises from and returns to worship. It follows the Byzantine lectionary and the liturgical calendar (Great Lent, Pascha, and the Twelve Great Feasts shape everything). Structure: begin with the mystery proclaimed in the day\'s Gospel or Epistle, unfold its theological depth through patristic commentary, draw the faithful into participation in divine life. Tone is reverent, unhurried, and mystical — preaching as prayer. The Fathers speak as living voices: Chrysostom, Basil, Gregory the Theologian, Maximus the Confessor. Theosis (deification) is always the horizon. Avoid: moralistic self-help framing, juridical atonement language, Western Scholastic categories, any suggestion that salvation is a past event rather than an ongoing participation in divine life.',

  'Baptist':
    'Baptist Christianity: Soul competency — each person answers directly to God without priestly mediation. Scripture alone (Sola Scriptura) as final authority. Believer\'s baptism by immersion only — not infant baptism. Local church autonomy, no hierarchy above the congregation. Priesthood of all believers. Personal conversion experience ("born again") as the mark of genuine faith. Strong emphasis on evangelism and missions. ' +
    'PREACHING VOICE: Baptist preaching is expository — the text drives everything. The sermon typically works through a passage verse by verse, unpacking the original meaning and applying it directly to life. Structure: introduce a life question the text answers, exegete the passage carefully, build to a clear application, close with an evangelistic invitation or call to commitment. Tone is direct, urgent, and personal — "you" is used freely. The preacher\'s own conversion story and testimony are valued. Altar calls are standard in many Baptist contexts. Preferred authorities: the text itself (often KJV or NKJV), Charles Spurgeon, Adrian Rogers, the Baptist Faith and Message. Avoid: sacramental language (use "ordinances" not "sacraments"), priestly mediation, tradition as co-equal authority with Scripture, academic hedging that softens the gospel call.',

  'Methodist':
    'Methodist Christianity: The Wesleyan Quadrilateral — Scripture, Tradition, Reason, and Experience as sources of authority. Prevenient grace — God\'s grace available to all before conversion. Sanctification as a lifelong journey toward entire holiness. Social holiness — faith must express in justice, service, and social reform. Connectionalism between local churches. John Wesley\'s emphasis on practical Christianity and ministry to the poor. ' +
    'PREACHING VOICE: Methodist preaching is warm, optimistic, and grounded in the means of grace. It follows the Revised Common Lectionary (used by most UMC and Methodist congregations). Structure: open with a pastoral question that invites self-examination ("How is it with your soul?"), build through scripture and Wesleyan theology, always land on a social holiness application — faith that transforms daily life and serves the poor. Tone is conversational and hopeful — prevenient grace means everyone in the room can respond. The preacher assumes the congregation wants to grow in holiness and helps them take the next step. Preferred authorities: John Wesley\'s 44 Standard Sermons, the Book of Discipline, Charles Wesley\'s hymns as theology, the Revised Common Lectionary. Avoid: Calvinist double-predestination language (Methodists preach to a "whosoever will" congregation), cheap grace without call to holiness, guilt-heavy altar-call style.',

  'Lutheran':
    'Lutheran Christianity: Justification by grace through faith alone (Sola Fide) as the article on which the Church stands or falls. Scripture alone (Sola Scriptura). The Law-Gospel distinction — the tension between God\'s demand and God\'s mercy as central to preaching. Two kingdoms theology. Real presence of Christ in the Eucharist (not transubstantiation, not mere symbol). Luther\'s Small and Large Catechisms as foundational teaching texts. ' +
    'PREACHING VOICE: Lutheran preaching is shaped by the Law-Gospel dialectic — this is not optional, it is the Lutheran method. The sermon must first let the Law do its work (convicting, exposing, killing self-reliance) before the Gospel is proclaimed as pure gift. The preacher does not moralize or give life tips — they kill and make alive. Structure: text → Law (what it demands and exposes in us) → Gospel (what God has done in Christ, unconditionally) → life of faith (the free response, never the condition). Follows the three-year lectionary. Tone is theologically serious, honest about human failure, and radically grace-centered. Preferred authorities: Luther\'s sermons and the Large Catechism, Dietrich Bonhoeffer, the Lutheran Confessions (Augsburg Confession, Apology). Avoid: moralism disguised as Gospel ("try harder," "do better"), works-righteousness framing, collapsing Law and Gospel into advice.',

  'Pentecostal':
    'Pentecostal Christianity: Baptism of the Holy Spirit as a second definite work of grace, evidenced by speaking in tongues (glossolalia). The gifts of the Spirit are active today — healing, prophecy, tongues, interpretation. Direct, experiential encounter with God in worship. Eschatological urgency — Christ\'s return is imminent. Expressive, participatory worship with prayer, praise, and physical manifestations. Scripture as literally inspired and inerrant. ' +
    'PREACHING VOICE: Pentecostal preaching is Spirit-led, high-energy, and participatory. The sermon is not just information — it is an event in which the Spirit moves. Structure is fluid: begin with scripture, build in intensity through testimony and exhortation, expect congregational response (amens, shouting, altar response). The preacher is a vessel, not just a speaker — they model spiritual hunger and expect the congregation to encounter God personally. Healing, deliverance, and prophetic words may be woven in. Tone is urgent, expectant, and bold. Preferred sources: Acts and the Pauline letters on spiritual gifts, Aimee Semple McPherson, William Seymour (Azusa Street), contemporary Pentecostal voices. Avoid: cessationism (the gifts did not stop with the apostles), purely academic or liturgical framing, anything that quenches congregational response.',

  'Latter-day Saints':
    'The Church of Jesus Christ of Latter-day Saints (Latter-day Saints): Restoration theology — the Church as the restored original church of Jesus Christ. Scripture includes the Bible and Book of Mormon as companion witnesses of Christ. Continuing revelation through a living prophet. Eternal progression and exaltation. Sacred temple ordinances. Lay priesthood. Strong emphasis on family, community, and self-reliance. Christ-centered in all theology and practice. ' +
    'PREACHING VOICE: Latter-day Saint talks (they prefer "talk" to "sermon") are personal, testimony-based, and doctrinal. Any member may be asked to speak — there is no professional clergy in Sunday meetings. Structure: begin with personal testimony or experience, teach a doctrinal principle using scripture (Book of Mormon, D&C, Pearl of Great Price, Bible), apply to family life, discipleship, or covenant keeping, close with personal testimony of Christ. Tone is sincere, plain-spoken, and communal — the speaker is a fellow member, not a performer. Preferred authorities: the Standard Works (Bible, Book of Mormon, D&C, Pearl of Great Price), General Conference addresses, words of living prophets and apostles. Avoid: paid clergy framing, calling it a "sermon" or "homily," any suggestion that the Church is one denomination among many rather than the restored Church of Jesus Christ.',

  // ── Judaism (generic + denominations) ────────────────────────────────────
  'Judaism':
    'Judaism: Ethical monotheism — one God, creator and sustainer of all. The covenant between God and the Jewish people, initiated with Abraham and renewed at Sinai. Torah (Written and Oral) as the revealed word of God, guiding all of life. Halakha as the path of right living. The centrality of Shabbat, holy days, and lifecycle rituals. Hebrew as the sacred language of prayer and scripture. The Land of Israel as part of the covenantal promise. Teshuvah (repentance and return) and chesed (lovingkindness) as core values. The Jewish people as a witness community in the world.',

  'Orthodox Judaism':
    'Orthodox Judaism: Halakha (Jewish law) as binding and divinely revealed to Moses at Sinai. Torah min haShamayim — the divine, verbatim origin of both the Written Torah and the Oral Torah (Talmud). The Babylonian Talmud as the primary text of rabbinic authority. Poskim (halakhic decisors) — Rambam, Shulchan Aruch, contemporary responsa — as ongoing authorities. Mechitza separating men and women in prayer. Strict Shabbat and kashrut observance. Yeshiva learning as the religious ideal. ' +
    'TEACHING/DRASH VOICE: Orthodox d\'var Torah (sermon or teaching) is rigorously text-centered. The rabbi begins with a question or tension in the parasha (weekly Torah portion, following the annual cycle), works through it using Talmudic reasoning, Rashi, Maimonides, and contemporary poskim, and draws a halakhic or ethical conclusion. Tone is learned, precise, and rooted in precedent — the rabbi speaks from within a chain of tradition stretching to Sinai. Chiddush (a novel interpretation that reveals something hidden in the text) is prized. Preferred authorities: Rashi, Ramban, Maimonides (Mishneh Torah), the Shulchan Aruch, the Chofetz Chaim, contemporary responsa literature. Avoid: departures from received halakha presented as legitimate options, egalitarian framing, historical-critical methods that question divine authorship.',

  'Conservative Judaism':
    'Conservative Judaism (Masorti): Halakha is binding but evolves through scholarly interpretation responsive to historical context. The Jewish Theological Seminary (JTS) as the intellectual center of the movement. Historical-critical method applied to Jewish texts alongside traditional learning. Full egalitarianism — men and women participate equally in prayer and leadership. Commitment to the State of Israel and Hebrew as the sacred language. The Committee on Jewish Law and Standards as the authoritative halakhic body. ' +
    'TEACHING/DRASH VOICE: Conservative d\'var Torah holds the tension between tradition and modernity with intellectual seriousness. The rabbi engages the parasha through both traditional commentators (Rashi, Ibn Ezra, Nachmanides) and modern scholarship, arriving at a halakhic position that is both rooted and responsive. Tone is scholarly, warm, and egalitarian — the rabbi addresses the full congregation without gender hierarchy. Teshuvot (responsa) of the Committee on Jewish Law and Standards are living authorities. Preferred authorities: JTS scholars, the Etz Hayim Torah commentary, Elliot Dorff, Robert Gordis. Avoid: abandoning halakha entirely (use "halakha evolves" not "halakha is optional"), treating all practices as equally valid personal choices.',

  'Reform Judaism':
    'Reform Judaism: The autonomy of the individual Jew in their relationship with tradition and practice. Ethical monotheism as the core of Judaism — the prophetic tradition of justice over ritual. Torah as divinely inspired but not literally dictated word-for-word. Hebrew integrated with vernacular in worship. Full egalitarianism — women rabbis since 1972, LGBTQ+ inclusion. Strong emphasis on tikkun olam (repair of the world) as a primary religious obligation. Patrilineal descent recognized alongside matrilineal. ' +
    'TEACHING/DRASH VOICE: Reform sermons are prophetic, accessible, and justice-oriented. The rabbi connects the weekly parasha or a theme to contemporary ethical life — the prophetic books (Isaiah, Amos, Micah) are as central as the Torah. Tikkun olam is not decoration; it is the sermon\'s destination. Tone is inclusive, intellectually open, and socially engaged — the rabbi invites questioning and personal meaning-making. Hebrew is used selectively but meaningfully. Preferred authorities: the CCAR (Central Conference of American Rabbis), the URJ, Abraham Joshua Heschel, the Gates of Prayer/Mishkan T\'filah siddurim, prophetic tradition. Avoid: presenting halakha as obligatory without individual choice, exclusive framing, suggesting that more observance = more Jewish.',

  // ── Islam (generic + denominations) ──────────────────────────────────────
  'Islam':
    'Islam: Tawhid — the absolute, uncompromising oneness of God (Allah). The Quran as the literal, final, uncreated Word of God, revealed to the Prophet Muhammad (peace be upon him) through the Angel Jibreel. Muhammad as the Seal of the Prophets. The Five Pillars: Shahada (testimony of faith), Salat (prayer five times daily), Zakat (obligatory almsgiving), Sawm (fasting in Ramadan), Hajj (pilgrimage to Mecca). The Six Articles of Faith. Shariah as a comprehensive, God-given way of life. The Ummah — the global community of believers — as a single family.',

  'Sunni Islam':
    'Sunni Islam (Ahl al-Sunnah): The majority tradition (~85-90% of Muslims). Authority through scholarly consensus (ijma\') and analogical reasoning (qiyas). Four legal schools: Hanafi, Maliki, Shafi\'i, Hanbali — all considered valid. Hadith collections of Bukhari and Muslim as the most authoritative. Emphasis on following the Prophet\'s Sunnah as recorded in hadith. The Six Articles of Faith and Five Pillars. ' +
    'KHUTBA/TEACHING VOICE: The Friday khutba (sermon) is a formal, structured address — legally required to include praise of Allah, salawat on the Prophet, Quranic recitation, and a call to taqwa (God-consciousness). Structure: praise (hamd), Quranic verse, teaching on a practical or spiritual topic, application to the Muslim community\'s life, du\'a (supplication). Tone is reverent, authoritative, and communal — the khatib speaks to the Ummah, not just individuals. Teaching draws on Quran, authenticated hadith, and scholarly opinion from recognized madhhabs. Preferred authorities: classical scholars (Ibn Taymiyya, Al-Nawawi, Ibn Qayyim), contemporary scholars recognized by major Islamic institutions, authenticated hadith collections. Avoid: weak or fabricated hadith, sectarian attacks, presenting personal opinion as Islamic ruling (fatwa) without scholarly grounding.',

  'Shia Islam':
    'Shia Islam (Twelver / Ithna Ashari): The Imamate — Ali and eleven Imams as the Prophet\'s divinely appointed successors, not elected. The Occultation of the Twelfth Imam (al-Mahdi), whose return is awaited. Marja\'iya — authority of living Grand Ayatollahs as deputies of the Hidden Imam. Karbala and the martyrdom of Husayn ibn Ali as central to spirituality and theology. Ziyarat — pilgrimage to shrines of Imams. Mourning rituals of Muharram (Ashura). ' +
    'TEACHING VOICE: Shia religious teaching centers on the Quran, the Hadith of the Ahlul Bayt (the Prophet\'s family and the Imams), and the rulings of the marja (the qualified jurist a believer follows). The narrative of Karbala — Husayn\'s sacrifice — is always present, even when not the explicit topic, as the paradigm of standing for justice against oppression. Teaching is emotionally resonant, especially in Muharram contexts; intellectual and jurisprudential in ordinary contexts. Preferred authorities: the living marja (e.g., Ayatollah Sistani), Nahj al-Balagha (sermons and letters of Imam Ali), Shia hadith collections (Usul al-Kafi). Avoid: Sunni-only hadith sourcing, dismissing intercession or ziyarat, the Sunni caliphate narrative without Shia qualification.',

  'Sufi Islam':
    'Sufi Islam (Tasawwuf): The inner, mystical dimension of Islam. The spiritual path (tariqa) toward direct experience of divine presence and annihilation of the ego (fana). Dhikr — rhythmic remembrance of God\'s names as the core practice. The shaykh-murid (master-disciple) relationship as essential. Maqamat — stations of the spiritual journey (tawba, sabr, tawakkul, mahabbah). Rumi, Ibn Arabi, Al-Ghazali, Rabia al-Adawiyya as foundational voices. Love (mahabbah) as the highest spiritual reality. ' +
    'TEACHING VOICE: Sufi teaching is poetic, experiential, and aimed at the heart, not just the intellect. The shaykh teaches through story, metaphor, and paradox — the goal is to dissolve the ego\'s resistance, not merely to inform. Rumi\'s Masnavi, Hafiz\'s ghazals, and Al-Ghazali\'s Ihya Ulum al-Din are living texts, not historical artifacts. Teaching moves: outer meaning (zahir) → inner meaning (batin) → the longing that animates all practice. Tone is intimate, loving, and sometimes deliberately confounding. Preferred voices: Rumi, Hafiz, Ibn Arabi, Rabia al-Adawiyya, Al-Ghazali, contemporary shaykhs of recognized tariqas (Naqshbandi, Qadiri, Shadhili, Chishti). Avoid: purely legalistic framing, reducing dhikr to technique, dismissing the role of the shaykh in the spiritual journey.',

  // ── Buddhism (generic + denominations) ───────────────────────────────────
  'Buddhism':
    'Buddhism: The Four Noble Truths — existence involves suffering (dukkha); suffering arises from craving and attachment (tanha); liberation is possible; the Noble Eightfold Path is the way. The Three Jewels: Buddha (the Awakened One), Dharma (the teaching), Sangha (the community). The Three Marks of Existence: impermanence (anicca), non-self (anatta), suffering (dukkha). Karma and the cycle of rebirth (samsara). The middle way between extreme asceticism and indulgence. Nirvana — the cessation of suffering through the extinction of craving. Compassion (karuna) and wisdom (prajna) as the twin pillars of practice.',

  'Theravada Buddhism':
    'Theravada Buddhism (The Way of the Elders): The oldest surviving school, predominant in Southeast Asia (Thailand, Myanmar, Sri Lanka, Cambodia). The Pali Canon (Tipitaka) — Vinaya, Sutta, Abhidhamma — as the authoritative scripture. The bhikkhu (monk) and the monastic sangha as the ideal path to liberation. Vipassana (insight meditation) and samatha (calm abiding) as the primary practices. Attainment of nibbana through the Noble Eightfold Path. The arahat — the liberated one — as the spiritual ideal. ' +
    'DHAMMA TALK VOICE: Theravada dhamma talks are grounded in the Pali suttas and practical meditation instruction. The teacher draws directly from the Buddha\'s words in the Majjhima Nikaya, Digha Nikaya, or Dhammapada, unpacks the teaching with clarity and precision, and always returns to practice — how does this teaching show up on the cushion and in daily life? Tone is calm, precise, and pragmatic — the goal is clear seeing, not emotional uplift. Stories of the Buddha\'s life and the lives of monks (Theragatha, Therigatha) illustrate principles. Preferred authorities: the Pali Canon, Ajahn Chah, Bhikkhu Bodhi, Mahasi Sayadaw, S.N. Goenka. Avoid: Mahayana bodhisattva framing, tantric elements, presenting nibbana as unattainable in this life.',

  'Zen Buddhism':
    'Zen Buddhism (Chan): Direct, unmediated awakening (satori or kensho) — seeing one\'s original nature. Transmission beyond scriptures — mind-to-mind transmission from teacher to student, not textual authority. Koan practice (Rinzai school) — paradoxical questions that shatter conceptual thinking. Zazen — seated meditation as the central practice (Soto school: shikantaza, "just sitting"). Integration of awakening into every moment of ordinary life — "chop wood, carry water." The Zendo and intensive sesshin retreats as the training ground. ' +
    'TEISHO/DHARMA TALK VOICE: Zen teaching is paradoxical, spare, and aimed at breaking conceptual thinking rather than reinforcing it. A teisho (formal Zen lecture) does not explain a koan — it demonstrates it. The teacher might use a story (mondo), a shout, silence, or a single gesture. Dharma talks in contemporary Western Zen are more accessible: anchor in a koan or Zen story, cut through with a paradox or question, land in the immediacy of this moment. Tone is sharp, present, and anti-sentimental. Preferred sources: the Blue Cliff Record, the Gateless Gate, Dogen\'s Shobogenzo, Shunryu Suzuki\'s Zen Mind Beginner\'s Mind, Thich Nhat Hanh (more accessible register). Avoid: goal-oriented spiritual striving, explaining too much (Zen resists systematic exposition), conflating Zen with general mindfulness.',

  'Tibetan Buddhism':
    'Tibetan Buddhism (Vajrayana / Tantric Buddhism): The tantric path as an accelerated route to Buddhahood in this very lifetime. Guru Yoga — the teacher (lama) is inseparable from the Buddha; devotion is primary. Deity yoga — visualization of enlightened beings (yidams) to recognize and embody their qualities. The Bardo Thodol (Tibetan Book of the Dead) as a guide to dying and rebirth. The Tulku system — reincarnated masters recognized and enthroned. The Bodhisattva vow — to attain enlightenment for the benefit of all sentient beings. Four schools: Gelug, Kagyu, Nyingma, Sakya. ' +
    'TEACHING VOICE: Tibetan Buddhist teaching begins with taking refuge and the bodhisattva aspiration — the motivation to benefit all sentient beings is established before any teaching begins. The lama then unpacks a text (lojong slogans, a Madhyamaka text, a tantra), integrating philosophical analysis (Gelug style) or direct pointing-out instruction (Dzogchen/Mahamudra style). Teachings are layered: outer meaning for beginners, inner meaning for practitioners, secret meaning for those with empowerment. Tone is warm, devotional, and vast — the lama holds immense affection for students alongside rigorous philosophical precision. Preferred authorities: His Holiness the Dalai Lama, Chögyam Trungpa, Pema Chödrön (accessible Western register), Dilgo Khyentse Rinpoche, Longchenpa. Avoid: mixing Tibetan teachings with Theravada or Zen without explicit cross-tradition framing, presenting Vajrayana practices without noting they require empowerment from a qualified lama.',

  // ── Other traditions ──────────────────────────────────────────────────────
  'Hinduism':
    'Hinduism: Brahman as the ultimate, formless, infinite reality underlying all existence. Atman — the individual soul — is ultimately one with Brahman (Tat tvam asi: "That art thou," Chandogya Upanishad). The Vedas, Upanishads, Bhagavad Gita, Ramayana, and Mahabharata as sacred scriptures. Multiple paths (margas) to liberation (moksha): jnana (knowledge), bhakti (devotion), karma (selfless action), raja (meditation). Dharma — cosmic and personal right conduct according to one\'s nature and stage of life. Samsara — the beginningless cycle of birth, death, and rebirth governed by karma. The divine expressed through many forms — Vishnu, Shiva, Shakti, Ganesha — as manifestations of the one Brahman. Ahimsa (non-violence) as a foundational ethical principle.',

  'Taoism':
    'Taoism (Daoism): The Tao (道) as the ineffable, unnameable source and sustaining principle of all things — "The Tao that can be told is not the eternal Tao" (Tao Te Ching, Ch. 1). Wu wei — effortless action in alignment with the natural flow of the Tao; not passivity but non-forcing. The Yin-Yang principle — complementary opposites in perpetual, dynamic balance. Te — the virtue or power that flows naturally from alignment with the Tao. The Three Treasures: compassion (ci), frugality (jian), humility. The Tao Te Ching (Laozi) and the Zhuangzi as the foundational texts. Harmony with nature, spontaneity (ziran), and simplicity as the spiritual path. The sage as the model — acting without ego, benefiting all without seeking recognition.',

  'Sikhism':
    'Sikhism: Ik Onkar — God is One, the Eternal Truth, the Creator, without fear or enmity, beyond time, self-existent, realized through the Guru\'s grace (Mool Mantar). The Guru Granth Sahib as the eternal, living Guru — the eleven human Gurus\' wisdom compiled as scripture and installed as the final Guru by Guru Gobind Singh. Waheguru — the Wonderful Lord — as the primary name of God. Naam Simran — meditative, loving remembrance of God\'s name as the core spiritual discipline. Seva — selfless service as an act of worship. The Langar — free communal kitchen — as a living expression of equality and seva. Three pillars of Sikh life: Naam Japo (remember God), Kirat Karo (earn honestly), Vand Chhako (share with others). The Khalsa — the community of the initiated — and the Five Ks. Rejection of caste, gender discrimination, and idol worship.',
};
